### ISSUE TITLE
ehm

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/arcade-mini-games#15]
https://github.com/WebAhead5/arcade-mini-games#play-crickets

**/play crickets** ?

# :laughing:

**Comment by MorisR** [comment]
![download](https://user-images.githubusercontent.com/10247681/81919645-c7788a00-95e0-11ea-98f3-868486fdbdaf.jpg)

![495739_1](https://user-images.githubusercontent.com/10247681/81919682-d2331f00-95e0-11ea-802e-1109616e1353.jpg)
![71zr+Lr3V5L _AC_SX425_](https://user-images.githubusercontent.com/10247681/81919701-d7906980-95e0-11ea-86a1-8a23ace28199.jpg)

![images](https://user-images.githubusercontent.com/10247681/81919760-eaa33980-95e0-11ea-918e-d8eb145ee599.jpg)
