### ISSUE TITLE
logout-button

### ISSUE THREAD

**Issue by Marwanrizik91** [WebAhead5/arcade-mini-games#17]
logout button actually only takes to the home page, 
you could have done something better, by saving name name to the local storage. then deleting it on clicking logout.
which will also solve another problem, which is refreshing the page when you are on the game, you will get undefined user on the top left corner.
https://github.com/WebAhead5/arcade-mini-games/issues/19#issue-618062432

**Comment by MoradAbed** [comment]
When clicking on logout, it deletes the user name that locally stored.
And you are logging out so the log out btn should delete the local storage and take you to the main home page. 
the back btn takes you to the game list.
