### ISSUE TITLE
XO

### ISSUE THREAD

**Issue by amirfahoum** [WebAhead5/arcade-mini-games#26]
the algorithm on XO game doesnt work in good way ,
![Screenshot from 2020-05-14 12-41-36](https://user-images.githubusercontent.com/47448606/81919321-5e911200-95e0-11ea-9dec-cdd239d4207b.png)

the 0 can beat me on the image but it didn't, it choose different wrong cells instead the right one to win...

**Comment by MorisR** [comment]
give it a try now
